#!/bin/sh
set -ev

# Directories.
root_dir=`pwd`
build_dir="$root_dir/_travis/build"

# Shortcuts.
git_clone="git clone --quiet --recursive"

# Create layout.
rm -rf "$build_dir"
mkdir -p "$build_dir"

# Source ROS setup file
. /opt/ros/indigo/setup.sh

# Compile
echo "--> Compiling urdf_parser_py"
cd "$root_dir"
cmake .
make
make test ARGS="-VV"
sudo make install
